Improve namespacing for chapter 1
MAO3J1m0Op/algebra-in-lean pull request #20
Opened 2024-07-06 14:57 UTC by MAO3J1m0Op

Because many of our names conflict with those defined in Mathlib, the current paradigm of namespacing and importing used in chapter 1 will not work when future chapters are introduced, as using the `open` keyword creates definition ambiguity between our definition and Mathlib's definition that Lean cannot solve.

Instead, we will place everything in one namespace. However, our currently used name of `Defs` is not very descriptive, so we'll instead use the namespace name `AlgebraInLean`.

2024-07-06 16:00 UTC, MithicSpirit requested changes
Imo this should delete Basic.lean as well.

2024-07-06 23:08 UTC, Stavan-Jain approved these changes
lgtm

2024-07-07 01:13 UTC, MithicSpirit approved these changes
lgtm

2024-07-07 01:13 UTC, MithicSpirit commented on AlgebraInLean.lean
Maybe run `lake exe mk_all` to build this, although that's not really necessary for this PR atm.

2024-07-07 21:43 UTC, justin-t-morrill commented
lgtm

2024-07-07 21:43 UTC, justin-t-morrill approved these changes

2024-07-08 17:26 UTC, AdamJasonKern approved these changes

2024-07-08 17:39 UTC, merged